### ISSUE TITLE
 Clone buildx step in workflow.yml is failing at the moment

### ISSUE THREAD

**Issue by aktech** [data-apis/python-record-api#83]
https://github.com/data-apis/python-record-api/blob/8694ef8f322e27e9fc529a8468403bf2946c83d5/.github/workflows/workflow.yml#L59

Here are the logs: https://github.com/data-apis/python-record-api/pull/78/checks?check_run_id=1120230770

**Comment by saulshanabrook** [comment]
Ah weird, it looks like github actions changed some permissioning:

```bash
##[error]Repository path '/tmp/buildx-source' is not under '/home/runner/work/python-record-api/python-record-api'
```

We were previously cloning the source `/tmp/...` and we need to clone it into our project directory instead?

Just need to make sure we delete it at the end then before we do any auto-pr actions
