### ISSUE TITLE
Koalas Not Tracing

### ISSUE THREAD

**Issue by saulshanabrook** [data-apis/python-record-api#90]
Koalas tests are now running, but they don't seem to be generating any traces? See http://167.172.14.45:2746/artifacts/argo/koalas-1.2.1-0-1-1/koalas-1.2.1-0-1-1-1410725124/main-logs for the successful logs. 

No traces generated: https://github.com/data-apis/python-record-api/pull/89

**Comment by ueshin** [comment]
@saulshanabrook Thanks for fixing this!
